dist: trusty
sudo: required
language: go
go: "1.12"

env: 
  - MONGODB_VER=mongodb-linux-x86_64-2.6.12 MINIO=2019-04-23T23-50-36Z WIRED_TIGER=false
  - MONGODB_VER=mongodb-linux-x86_64-3.6.8  MINIO=2019-04-23T23-50-36Z WIRED_TIGER=false
  - MONGODB_VER=mongodb-linux-x86_64-3.6.8  MINIO=2019-04-23T23-50-36Z WIRED_TIGER=true

install:
  - export GO111MODULE=on

  # set up minio
  - wget https://dl.minio.io/server/minio/release/linux-amd64/archive/minio.RELEASE.$MINIO -O minio
  - chmod a+x minio
  - export MINIOD=`pwd`/minio

  # set up mongo
  - cd ..
  - wget http://fastdl.mongodb.org/linux/$MONGODB_VER.tgz
  - tar xfz $MONGODB_VER.tgz
  - export MONGOD=`pwd`/$MONGODB_VER/bin/mongod
  - cd -

  # set up jars
  - cd ..
  - git clone https://github.com/kbase/jars
  - export JARSDIR=`pwd`/jars/lib/jars/
  - cd -


  # set up test config
  - cp test.cfg.example test.cfg
  - sed -i "s#^test.minio.exe.*#test.minio.exe=$MINIOD#" test.cfg
  - sed -i "s#^test.mongo.exe.*#test.mongo.exe=$MONGOD#" test.cfg
  - sed -i "s#^test.jars.dir.*#test.jars.dir=$JARSDIR#" test.cfg
  - sed -i "s#^test.mongo.wired_tiger.*#test.mongo.wired_tiger=$WIRED_TIGER#" test.cfg
  - cat test.cfg

script:
  - go build app/blobstore.go

  # run tests
  - export TCFG=`pwd`/test.cfg
  - BLOBSTORE_TEST_CFG=$TCFG go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)