dist: trusty
sudo: required
language: go
go: "1.12"

env: 
  - MONGODB_VER=mongodb-linux-x86_64-2.6.12 MINIO=2019-05-23T00-29-34Z WIRED_TIGER=false
  - MONGODB_VER=mongodb-linux-x86_64-3.6.8  MINIO=2019-05-23T00-29-34Z WIRED_TIGER=false
  - MONGODB_VER=mongodb-linux-x86_64-3.6.8  MINIO=2019-05-23T00-29-34Z WIRED_TIGER=true

install: true

# install dependencies in script vs install because the deploy job below makes install run
# That fails because there are no matrix env varables set
script: 
  - export GO111MODULE=on

  # set up minio
  - wget https://dl.minio.io/server/minio/release/linux-amd64/archive/minio.RELEASE.$MINIO -O minio
  - chmod a+x minio
  - export MINIOD=`pwd`/minio

  # set up mongo
  - cd ..
  - wget http://fastdl.mongodb.org/linux/$MONGODB_VER.tgz
  - tar xfz $MONGODB_VER.tgz
  - export MONGOD=`pwd`/$MONGODB_VER/bin/mongod
  - cd -

  # set up jars
  - cd ..
  - git clone https://github.com/kbase/jars
  - export JARSDIR=`pwd`/jars/lib/jars/
  - cd -

  # set up test config
  - cp test.cfg.example test.cfg
  - sed -i "s#^test.minio.exe.*#test.minio.exe=$MINIOD#" test.cfg
  - sed -i "s#^test.mongo.exe.*#test.mongo.exe=$MONGOD#" test.cfg
  - sed -i "s#^test.jars.dir.*#test.jars.dir=$JARSDIR#" test.cfg
  - sed -i "s#^test.mongo.wired_tiger.*#test.mongo.wired_tiger=$WIRED_TIGER#" test.cfg
  - cat test.cfg

  # build the executable
  - go build app/blobstore.go

  # run tests
  - export TCFG=`pwd`/test.cfg
  - BLOBSTORE_TEST_CFG=$TCFG go test -race -coverprofile=coverage.txt -covermode=atomic ./...

jobs:
  include:
    - stage: deploy
      env: # The following are secure declarations for DOCKER_USER, DOCKER_PASS
        - secure: "kxGkKy+0CRgbmd1GYk5mvvSMsp/lIVLLyHrCpakTziMSArX9MV4SX+7Ep7GrQKbtvQvGXPQXSY5WNwUxvznRm1nMzKdo7Kx8IZ5+xvEN0GuBmj5w3jjZcXWrUt9jFUfdFu1eoFIfkvZuzEv9RR/u1pL5jKkyL9PWKRdBHQR7SjcGpxLhenD5ya4g9Exg585YGZWFOSMsh14SyrSHVkw9OdW2LF3qndMksvkxfWBDlkM/b/zo/tlDjppE9vTJ/pEFQAVe/eEPK04F10wqXm5ltWAPFT1KONGSN03sYdxKOtoScTi485DNAdra6tSa3kLtTLfZpVF9Cv2xkJEtIeXnFu33nSHpEX1d9f1z8kIfALUNefVLz8vgQ922pHLGTpGUIaMCSs6gOuDpR4xxJSjJLVj99rpSnxwJz5FFQWLkcMfzVydnzSWVzLgvH+QYuu+s09C4j4skFrScUOXKJHRXtzA4tmy1DoCF/NmB39ugezca7Qfshr/o5PmxaJTSIe/dw6HRTKzs9h0HgXX2A58H7Ssj2UV1a7VttogjM3jxrsAphxWG0u817hrLIkMUpUH8rpJDLOVTJgoQp+na04DDsnc7OWy0YjGDwrXF6gcTgKSXS28TEAavNh8+VB8/9vVHfF0SKtkiBrz71MQR3N58ljgUND2m4KtJ1Kvw9++Gpg4="
        - secure: "ReqjYlBnxY5mWQBMPCsccg5LhYV6jr0+RbKA/RMmDpStNPUx/D7pcdXzPZ8eXCdsycceIPFFtr7Oa9+UdBaRec0DsbhczdtvpFQFDZhaLnTtYZ5Ia9pYUICQwnUvpEFq3owbSocD7oV0f0nIakCx+xj4/NVqnyvplmD4FiF5IA8N/mwXXxqHK+oPussqrVb/mna4KOlIGcuhVA2Gi0KvLqAu70KkMXmgbU9/4oITzZURKoj1zdNDNQJ3Q+QLXwe+6251wBCj5LliZ7H4p21vAHHtkF1uCveBZjeea1gI1xQa3b69WBZQvdAgTdXar4U0mzHv2bnd3JCP6F7oCVsCHrM1hsKSPBZRHEMJzi+ip7qUlooOcx+/bnj4U8jQF90fXY4qeKshAMJnpdUGSMIRInJ9spddXxSHXCrbCggQGhc8toLlcMAHmBfpKpBqxv9LneBkFQYymfA4vwcwdFSP+JGS4Vwa+qaN85M69see1HxLBVOCjdrgJsO3Zayof7YiQYSS2eJLcaj+BTiccUQHPJmg2trwJcnI5VasJuBZVtTmwR6PZxQZgbs6qBC4YyEyiezH2xIjSCAZhhC38o2PmdfXO9QPlhOqJhCUpfM9rJq5si1l+mSISquWqz+65yjM8IS+GOpDXcBAZsvibyzxSi2PeM/sB5gByDAgNI3qqVY="
      script: # Only push to dockerhub if this isn't a PR and we're updating master or develop
        - build/build_docker_image.sh
        - IMAGE_NAME=kbase/blobstore build/push2dockerhub.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)