version: "3.1"
# This is just an example that shows the relationships between the blobstore image
# and other services. Many of these things would be overidden in the actual
# deployment docker-compose file - for example, the name of the mongodb instance
# that is started up and polled
services:
  kbase_blobstore:
    image: kbase/blobstore:latest
    ports:
      - "8080:8080"
    environment:
      blobstore_host: 0.0.0.0:8080
      mongo_host: localhost:27017
      mongo_database: dc_blobstore_test
      kbase_auth_url: https://ci.kbase.us/services/auth
      kbase_auth_admin_roles: KBASE_ADMIN,BLOBSTORE_ADMIN
      s3_host: minio:9000
      s3_bucket: blobbucket
      s3_access_key: mykey
      s3_access_secret: mysekrit
      s3_region: us-west-1
      s3_disable_ssl: "true"
      # add more configurations here
    command:
      - "-multiline"
      - "-wait"
      - "tcp://ci-mongo:27017"
      - "-wait"
      - "tcp://mongoinit:8080"
      - "-wait"
      - "tcp://minio:9000"
      - "-timeout"
      - "120s"
      - "-template"
      - "/kb/deployment/conf/deployment.cfg.templ:/kb/deployment/conf/deployment.cfg"
      - "/kb/deployment/blobstore/blobstore"
      - "--conf"
      - "/kb/deployment/conf/deployment.cfg"
      # If you needed to pass in context for template evaluation you would put something like
      # these lines that tell dockerize to hit github for an INI style file for the context
    # - "-env"
    # - "https://raw.githubusercontent.com/kbase/mini_kb/master/deployment/conf/tauth2-minikb.yml"
      # If the -env URL needs authentication you would use an -env-header directive that specified
      # either the hard coded string for the header, or a path to a file that contains the header
      # string ( used for working with docker secrets files)
    # - "-env-header"
    # - "AUTHORIZATION:authtokenvalue"
      # or for a path to a secrets file:
    # - "env-header"
    # - "/run/secrets/authheader"
      # If your server is using self-signed certs, or otherwise problematic for cert validation
      # you can add the following flag:
    # - "-validateCert=false"
    depends_on: ["ci-mongo", "mongoinit", "minio"]

  mongoinit:
    image: kbase/db_initialize:latest
    entrypoint:
      - "/kb/deployment/bin/dockerize.sh"
      - "-wait"
      - "tcp://ci-mongo:27017"
      - "-timeout"
      - "120s"
    depends_on: [ "ci-mongo" ]
  
  ci-mongo:
    image: mongo:2
    command:
      - "--smallfiles"
    ports:
      - "27017:27017"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=mykey
      - MINIO_SECRET_KEY=mysekrit
    command: server /data