version: "3.1"
# This is just an example that shows the relationships between the blobstore image
# and other services. Many of these things would be overidden in the actual
# deployment docker-compose file - for example, the name of the mongodb instance
# that is started up and polled
services:
  kbase_blobstore:
    build: .
    ports:
      - "8080:8080"
    environment:
      blobstore_host: 0.0.0.0:8080
      mongodb_host: mongo:27017
      mongodb_database: dc_blobstore_test
      kbase_auth_url: https://ci.kbase.us/services/auth
      kbase_auth_admin_roles: KBASE_ADMIN,BLOBSTORE_ADMIN
      s3_host: minio:9000
      s3_bucket: blobbucket
      s3_access_key: mykey
      s3_access_secret: mysekrit
      s3_region: us-west-1
      s3_disable_ssl: "true"
      # add more configurations here
    command:
      - "-multiline"
      - "-wait"
      - "tcp://mongo:27017"
      - "-wait"
      - "tcp://minio:9000"
      - "-timeout"
      - "120s"
      - "-template"
      - "/kb/deployment/conf/deployment.cfg.templ:/kb/deployment/conf/deployment.cfg"
      - "/kb/deployment/blobstore/blobstore"
      - "--conf"
      - "/kb/deployment/conf/deployment.cfg"
    depends_on: ["mongo", "minio"]
  
  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=mykey
      - MINIO_SECRET_KEY=mysekrit
    command: server /data